version: '3.1'

services:
  db:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: amp
      MYSQL_USER: carlos
      MYSQL_PASSWORD: pass123
      MYSQL_ROOT_PASSWORD: pass123
    expose:
      - "3306"
    volumes:
      - db:/var/lib/mysql
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql

  app1:
    build: .
    depends_on:
      - db
  
  app2:
    build: .
    depends_on:
      - db

  load-balancer:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2

volumes:
  db: