---
- name: Copy application files
  copy:
    src: ../../../
    dest: /app/

- name: Install Python docker module
  pip:
    name:
      - docker>=1.8.0
      - PyYAML>=3.11
      - docker-compose>=1.7.0

- name: Execute docker compose
  docker_compose:
    project_src: /app/
    state: present